# Generated by Django 6.0.3 on 2026-04-26 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('point_service', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_crees', to='transactions.admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='transactions.admin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants_crees', to='transactions.admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant',
                'verbose_name_plural': 'Assistants',
            },
        ),
        migrations.CreateModel(
            name='ApprovisionnementDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('admin', 'Administrateur'), ('assistant', 'Assistant')], default='admin', max_length=20)),
                ('type_approvisionnement', models.CharField(choices=[('cash', '💰 Cash'), ('uv', '📱 UV Touspiont'), ('wave', '💳 Wave')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvisionnements_emis', to='transactions.admin')),
                ('agent_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements_recus', to='transactions.agent')),
                ('assistant_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvisionnements_emis', to='transactions.assistant')),
            ],
            options={
                'verbose_name': 'Approvisionnement direct',
                'verbose_name_plural': 'Approvisionnements directs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_cash', models.DecimalField(decimal_places=2, default=0, help_text='Solde en espèces physiques', max_digits=12)),
                ('solde_uv', models.DecimalField(decimal_places=2, default=0, help_text='Solde UV Touspiont (Orange/Malitel/Telecel)', max_digits=12)),
                ('solde_wave', models.DecimalField(decimal_places=2, default=0, help_text='Solde Wave', max_digits=12)),
                ('solde_cash_hier', models.DecimalField(decimal_places=2, default=0, help_text="Solde Cash d'hier (fixe)", max_digits=12)),
                ('solde_uv_hier', models.DecimalField(decimal_places=2, default=0, help_text="Solde UV d'hier (fixe)", max_digits=12)),
                ('solde_wave_hier', models.DecimalField(decimal_places=2, default=0, help_text="Solde Wave d'hier (fixe)", max_digits=12)),
                ('last_balance_update', models.DateField(blank=True, null=True)),
                ('limite_cash', models.DecimalField(decimal_places=2, default=10000000, max_digits=12)),
                ('limite_uv', models.DecimalField(decimal_places=2, default=50000000, max_digits=12)),
                ('limite_wave', models.DecimalField(decimal_places=2, default=50000000, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caisse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
            },
        ),
        migrations.CreateModel(
            name='CompteEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulaire', models.CharField(max_length=200)),
                ('numero_compte', models.CharField(max_length=50, unique=True)),
                ('solde', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='DemandeApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_type', models.CharField(choices=[('admin', 'Administrateur'), ('assistant', 'Assistant')], default='admin', max_length=20)),
                ('type_echange', models.CharField(choices=[('uv_to_cash', '📱 UV → Cash'), ('wave_to_cash', '💳 Wave → Cash'), ('cash_to_uv', '💰 Cash → UV'), ('cash_to_wave', '💰 Cash → Wave')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('valide', '✅ Validé'), ('refuse', '❌ Refusé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_approvisionnement', to='transactions.agent')),
                ('assistant_destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recues', to='transactions.assistant')),
                ('traite_par_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees_admin', to='transactions.admin')),
                ('traite_par_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees_assistant', to='transactions.assistant')),
            ],
            options={
                'verbose_name': "Demande d'approvisionnement",
                'verbose_name_plural': "Demandes d'approvisionnement",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_rembourse', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('date_remboursement_complet', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('payee', 'Payée')], default='active', max_length=20)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('debiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='transactions.agent')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facture', models.CharField(choices=[('cliente', 'Facture Client - Client nous doit'), ('fournisseur', 'Facture Fournisseur - Nous devons')], default='cliente', max_length=20)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('personne_nom', models.CharField(max_length=200)),
                ('personne_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personne_telephone', models.CharField(blank=True, max_length=50)),
                ('montant_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('date_paiement_complet', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=30)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='OperationCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('interet', 'Intérêt crédité')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='transactions.compteepargne')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('uv', 'UV Touchpiont'), ('wave', 'UV Wave'), ('virement', 'Virement bancaire')], max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='transactions.facture')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('uv', 'UV Touchpiont'), ('wave', 'UV Wave')], max_length=20)),
                ('date_remboursement', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='transactions.dette')),
            ],
            options={
                'ordering': ['-date_remboursement'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent'), ('assistant', 'Assistant')], default='agent', max_length=20)),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('wave', 'Wave'), ('malitel', 'Malitel'), ('telecel', 'Telecel')], max_length=10)),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('credit', 'Crédit/Recharge')], max_length=10)),
                ('numero_client', models.CharField(max_length=20)),
                ('nom_client', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_operateur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('reference_operateur', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(default='complete', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assistant_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_assistant', to='transactions.admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
