# Generated by Django 6.0.3 on 2026-03-30 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('point_service', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='ApprovisionnementDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_approvisionnement', models.CharField(choices=[('cash', '💰 Cash'), ('uv', '📱 UV Touspiont'), ('wave', '💳 Wave')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='transactions.admin')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='transactions.agent')),
            ],
            options={
                'verbose_name': 'Approvisionnement direct',
                'verbose_name_plural': 'Approvisionnements directs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_cash', models.DecimalField(decimal_places=2, default=0, help_text='Solde en espèces physiques', max_digits=12)),
                ('solde_uv', models.DecimalField(decimal_places=2, default=0, help_text='Solde UV Touspiont (Orange/Malitel/Telecel)', max_digits=12)),
                ('solde_wave', models.DecimalField(decimal_places=2, default=0, help_text='Solde Wave', max_digits=12)),
                ('limite_cash', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
                ('limite_uv', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('limite_wave', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caisse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
            },
        ),
        migrations.CreateModel(
            name='DemandeApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echange', models.CharField(choices=[('uv_to_cash', '📱 UV → Cash'), ('wave_to_cash', '💳 Wave → Cash'), ('cash_to_uv', '💰 Cash → UV'), ('cash_to_wave', '💰 Cash → Wave')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('valide', '✅ Validé'), ('refuse', '❌ Refusé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='transactions.agent')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='transactions.admin')),
            ],
            options={
                'verbose_name': "Demande d'approvisionnement",
                'verbose_name_plural': "Demandes d'approvisionnement",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('wave', 'Wave'), ('malitel', 'Malitel'), ('telecel', 'Telecel')], max_length=10)),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('credit', 'Crédit/Recharge')], max_length=10)),
                ('numero_client', models.CharField(max_length=20)),
                ('nom_client', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_operateur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('reference_operateur', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(default='complete', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
