# Generated by Django 6.0.3 on 2026-05-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.RemoveField(
            model_name='facture',
            name='personne_email',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='type_facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='type_transaction',
            field=models.CharField(default=111111, help_text='Ex: Client nous doit, Fournisseur, Partenaire, etc...', max_length=255, verbose_name='Type de transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='personne_nom',
            field=models.CharField(max_length=200, verbose_name='Nom du client / tiers'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='personne_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
    ]
