# Generated by Django 6.0.3 on 2026-04-28 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEpargneAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulaire', models.CharField(max_length=200)),
                ('solde', models.BigIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_epargne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Decaissement')], max_length=20)),
                ('montant', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='transactions.caisse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('depot', 'Depot'), ('retrait', 'Retrait')], max_length=20)),
                ('montant', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='transactions.compteepargneadmin')),
            ],
        ),
    ]
