# Generated by Django 6.0.3 on 2026-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='last_balance_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caisse',
            name='solde_cash_hier',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Solde Cash d'hier (fixe)", max_digits=12),
        ),
        migrations.AddField(
            model_name='caisse',
            name='solde_uv_hier',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Solde UV d'hier (fixe)", max_digits=12),
        ),
        migrations.AddField(
            model_name='caisse',
            name='solde_wave_hier',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Solde Wave d'hier (fixe)", max_digits=12),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='limite_cash',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='limite_uv',
            field=models.DecimalField(decimal_places=2, default=50000000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='limite_wave',
            field=models.DecimalField(decimal_places=2, default=50000000, max_digits=12),
        ),
    ]
