# Generated by Django 6.0.3 on 2026-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_facture_options_remove_facture_personne_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='type_transaction',
            new_name='type_facture',
        ),
        migrations.AddField(
            model_name='agent',
            name='mot_de_passe_clair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='limite_uv',
            field=models.DecimalField(decimal_places=2, default=500000000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='limite_wave',
            field=models.DecimalField(decimal_places=2, default=500000000, max_digits=12),
        ),
    ]
