# Generated by Django 6.0.3 on 2026-04-28 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_compteepargneadmin_operationcaisse_operationepargne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationcaisse',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_caisse', to='transactions.caisse'),
        ),
        migrations.CreateModel(
            name='OperationUv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('ajout', 'Ajout'), ('retrait', 'Retrait')], max_length=20)),
                ('type_uv', models.CharField(choices=[('touchpoint', 'UV Touchpoint'), ('wave', 'UV Wave')], max_length=20)),
                ('montant', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_uv', to='transactions.caisse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
