# Generated by Django 6.0.3 on 2026-04-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_operationcaisse_caisse_operationuv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compteepargneadmin',
            options={'verbose_name': 'Compte epargne admin', 'verbose_name_plural': 'Comptes epargne admin'},
        ),
        migrations.AlterModelOptions(
            name='operationcaisse',
            options={'ordering': ['-date_operation']},
        ),
        migrations.AlterModelOptions(
            name='operationepargne',
            options={'ordering': ['-date_operation']},
        ),
        migrations.AlterModelOptions(
            name='operationuv',
            options={'ordering': ['-date_operation']},
        ),
    ]
