# Generated by Django 6.0.3 on 2026-05-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_printqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('decaissement', "Ajout (Donné à l'agent)"), ('encaissement', "Retrait (Récupéré de l'agent)")], max_length=20)),
                ('operateur_type', models.CharField(choices=[('admin', 'Administrateur'), ('assistant', 'Assistant')], max_length=20)),
                ('operateur_nom', models.CharField(max_length=100)),
                ('montant_cash', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('montant_uv', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('montant_wave', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_operations', to='transactions.agent')),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
    ]
