# Generated by Django 6.0.3 on 2026-05-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_historiqueagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('wave', 'Wave'), ('malitel', 'Malitel'), ('telecel', 'Telecel')], max_length=10)),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('credit', 'Crédit/Recharge')], max_length=10)),
                ('taux', models.DecimalField(decimal_places=4, help_text='Taux en décimal (ex: 0.0014 = 0.14%)', max_digits=6)),
            ],
            options={
                'verbose_name': 'Taux de commission',
                'verbose_name_plural': 'Taux de commission',
                'unique_together': {('operateur', 'type_transaction')},
            },
        ),
    ]
