# Generated by Django 6.0.3 on 2026-05-31 01:01

from django.db import migrations


def populate_rates(apps, schema_editor):
    CommissionRate = apps.get_model('transactions', 'CommissionRate')

    rates = [
        ('orange', 'depot', 0.0014),
        ('orange', 'retrait', 0.0028),
        ('orange', 'credit', 0.005),
        ('wave', 'depot', 0.01),
        ('wave', 'retrait', 0.01),
        ('wave', 'credit', 0),
        ('malitel', 'depot', 0.0014),
        ('malitel', 'retrait', 0.0028),
        ('malitel', 'credit', 0.005),
        ('telecel', 'depot', 0),
        ('telecel', 'retrait', 0),
        ('telecel', 'credit', 0.005),
    ]

    for operateur, type_transaction, taux in rates:
        CommissionRate.objects.get_or_create(
            operateur=operateur,
            type_transaction=type_transaction,
            defaults={'taux': taux}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_commissionrate'),
    ]

    operations = [
        migrations.RunPython(populate_rates),
    ]
