# Generated by Django 6.0.3 on 2026-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_annule_par_transaction_date_annulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnementdirect',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvisionnementdirect',
            name='statut',
            field=models.CharField(choices=[('entente', 'Entente'), ('valide', 'Valide')], default='entente', max_length=10),
        ),
        migrations.AddField(
            model_name='approvisionnementdirect',
            name='type_operation',
            field=models.CharField(choices=[('envoi', 'Envoi'), ('retrait', 'Retrait')], default='envoi', max_length=10),
        ),
        migrations.AlterField(
            model_name='approvisionnementdirect',
            name='type_approvisionnement',
            field=models.CharField(choices=[('cash', 'Argent'), ('uv', 'UV Touchpoint'), ('wave', 'UV Wave')], max_length=10),
        ),
    ]
