# Generated by Django 6.0.6 on 2026-08-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_approvisionnementdirect_date_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='transactions.agent'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='transactions.admin'),
        ),
    ]
