# Generated by Django 6.0.6 on 2026-08-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_assistant_agent_alter_assistant_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='telephone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='numero_client',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
