# Generated by Django 6.0.6 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_agent_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='numero_client',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wave_qr_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
